// 30 demo listings across Portland OR, Seattle WA, Austin TX.
// Prices in cents. For RENT mode, price is the monthly rent in cents.
import type { RawListing } from "./listing-provider";

// Helper: posted N hours ago (relative to import time so seeding always looks fresh)
const ago = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();

export const SEED_LISTINGS: RawListing[] = [
  // ── Portland, OR ──────────────────────────────────────────
  {
    id: "mock:pdx-001", source: "mock", mode: "BUY", price: 68500000, address: "142 Larkspur Lane",
    hood: "Sellwood", city: "Portland, OR", state: "OR", zip: "97202", lat: 45.4623, lng: -122.6582,
    beds: 3, baths: 2, sqft: 1840, lotSqft: 6100, yearBuilt: 1924, propertyType: "HOUSE",
    features: ["garden", "fenced-yard", "walkable", "fireplace"],
    description: "Light-filled craftsman with reworked kitchen, original fir floors, and a fenced back garden two blocks from the river path.",
    photos: [], postedAt: ago(2),
  },
  {
    id: "mock:pdx-002", source: "mock", mode: "BUY", price: 72900000, address: "88 Maple Court",
    hood: "Mount Tabor", city: "Portland, OR", state: "OR", zip: "97215", lat: 45.5118, lng: -122.5959,
    beds: 4, baths: 2.5, sqft: 2210, lotSqft: 7800, yearBuilt: 1968, propertyType: "HOUSE",
    features: ["garage", "fenced-yard", "fireplace"],
    description: "Mid-century split-level backing onto the park, with a two-car garage and a deep, tree-lined yard.",
    photos: [], postedAt: ago(5),
  },
  {
    id: "mock:pdx-003", source: "mock", mode: "RENT", price: 265000, address: "410 Belmont St #3B",
    hood: "Buckman", city: "Portland, OR", state: "OR", zip: "97214", lat: 45.5165, lng: -122.6531,
    beds: 2, baths: 1, sqft: 940, lotSqft: null, yearBuilt: 2019, propertyType: "APARTMENT",
    features: ["in-unit-laundry", "pet-friendly", "balcony", "elevator"],
    description: "Corner two-bed in a small modern building, with in-unit laundry, a private balcony, and bike storage downstairs.",
    photos: [], postedAt: ago(1),
  },
  {
    id: "mock:pdx-004", source: "mock", mode: "RENT", price: 197500, address: "23 Clinton Row",
    hood: "Division", city: "Portland, OR", state: "OR", zip: "97202", lat: 45.5045, lng: -122.6517,
    beds: 1, baths: 1, sqft: 680, lotSqft: null, yearBuilt: 2021, propertyType: "APARTMENT",
    features: ["pet-friendly", "rooftop", "transit", "walkable"],
    description: "Bright one-bedroom steps from the Division corridor, shared rooftop deck, walk score of 94.",
    photos: [], postedAt: ago(28),
  },
  {
    id: "mock:pdx-005", source: "mock", mode: "BUY", price: 61500000, address: "7 Alder Way",
    hood: "Woodstock", city: "Portland, OR", state: "OR", zip: "97206", lat: 45.4806, lng: -122.6307,
    beds: 3, baths: 1.5, sqft: 1560, lotSqft: 4800, yearBuilt: 1941, propertyType: "HOUSE",
    features: ["garden", "fireplace"],
    description: "Tidy cottage with a wood-burning fireplace, raised garden beds, and a detached studio that works as an office.",
    photos: [], postedAt: ago(48),
  },
  {
    id: "mock:pdx-006", source: "mock", mode: "BUY", price: 54200000, address: "301 Powell Loop",
    hood: "Brooklyn", city: "Portland, OR", state: "OR", zip: "97202", lat: 45.4853, lng: -122.6437,
    beds: 2, baths: 2, sqft: 1320, lotSqft: null, yearBuilt: 2016, propertyType: "TOWNHOME",
    features: ["garage", "new-build", "rooftop"],
    description: "Efficient newer townhome with attached garage and rooftop terrace.",
    photos: [], postedAt: ago(72),
  },
  {
    id: "mock:pdx-007", source: "mock", mode: "RENT", price: 320000, address: "55 Hawthorne Way",
    hood: "Hawthorne", city: "Portland, OR", state: "OR", zip: "97214", lat: 45.5121, lng: -122.6225,
    beds: 3, baths: 2, sqft: 1450, lotSqft: null, yearBuilt: 2014, propertyType: "TOWNHOME",
    features: ["in-unit-laundry", "garage", "dishwasher", "ac"],
    description: "Three-bed townhome on a quiet block off Hawthorne, with an attached garage and in-unit laundry.",
    photos: [], postedAt: ago(8),
  },
  {
    id: "mock:pdx-008", source: "mock", mode: "BUY", price: 89500000, address: "920 Alameda Ridge",
    hood: "Alameda", city: "Portland, OR", state: "OR", zip: "97212", lat: 45.5547, lng: -122.6391,
    beds: 4, baths: 3, sqft: 2640, lotSqft: 6800, yearBuilt: 1929, propertyType: "HOUSE",
    features: ["garden", "garage", "basement", "fireplace"],
    description: "Stately 1920s home with original woodwork, formal gardens, and a finished basement.",
    photos: [], postedAt: ago(96),
  },
  {
    id: "mock:pdx-009", source: "mock", mode: "RENT", price: 230000, address: "12 Lloyd Tower #1408",
    hood: "Lloyd", city: "Portland, OR", state: "OR", zip: "97232", lat: 45.5345, lng: -122.6577,
    beds: 1, baths: 1, sqft: 720, lotSqft: null, yearBuilt: 2008, propertyType: "CONDO",
    features: ["doorman", "elevator", "pool", "transit", "ac"],
    description: "High-floor one-bed with city + river views, full-service building, pool and gym.",
    photos: [], postedAt: ago(36),
  },
  {
    id: "mock:pdx-010", source: "mock", mode: "BUY", price: 47500000, address: "2210 SE 30th",
    hood: "Richmond", city: "Portland, OR", state: "OR", zip: "97202", lat: 45.5045, lng: -122.6358,
    beds: 2, baths: 1, sqft: 1100, lotSqft: 4200, yearBuilt: 1953, propertyType: "HOUSE",
    features: ["garden", "fenced-yard", "walkable"],
    description: "Cozy bungalow on a deep lot, fenced yard, ready for cosmetic updates.",
    photos: [], postedAt: ago(120),
  },

  // ── Seattle, WA ───────────────────────────────────────────
  {
    id: "mock:sea-001", source: "mock", mode: "BUY", price: 84500000, address: "315 Capitol Way E",
    hood: "Capitol Hill", city: "Seattle, WA", state: "WA", zip: "98102", lat: 47.6253, lng: -122.3209,
    beds: 3, baths: 2, sqft: 1720, lotSqft: 3600, yearBuilt: 1908, propertyType: "HOUSE",
    features: ["fireplace", "walkable", "transit"],
    description: "Classic Capitol Hill craftsman, walkable to Cal Anderson and the light rail.",
    photos: [], postedAt: ago(3),
  },
  {
    id: "mock:sea-002", source: "mock", mode: "RENT", price: 285000, address: "1500 Westlake Ave N",
    hood: "South Lake Union", city: "Seattle, WA", state: "WA", zip: "98109", lat: 47.6306, lng: -122.3373,
    beds: 1, baths: 1, sqft: 740, lotSqft: null, yearBuilt: 2018, propertyType: "APARTMENT",
    features: ["in-unit-laundry", "ac", "elevator", "transit", "ev-charger"],
    description: "Sleek SLU one-bed with floor-to-ceiling windows, EV charger access in garage.",
    photos: [], postedAt: ago(6),
  },
  {
    id: "mock:sea-003", source: "mock", mode: "BUY", price: 92500000, address: "2210 Queen Anne Ave",
    hood: "Queen Anne", city: "Seattle, WA", state: "WA", zip: "98109", lat: 47.6364, lng: -122.3565,
    beds: 4, baths: 2.5, sqft: 2380, lotSqft: 4500, yearBuilt: 1925, propertyType: "HOUSE",
    features: ["garden", "fireplace", "garage", "basement"],
    description: "Queen Anne classic with sound views from the upper floor, formal garden.",
    photos: [], postedAt: ago(10),
  },
  {
    id: "mock:sea-004", source: "mock", mode: "RENT", price: 360000, address: "88 Yesler Way #602",
    hood: "Pioneer Square", city: "Seattle, WA", state: "WA", zip: "98104", lat: 47.6018, lng: -122.3318,
    beds: 2, baths: 2, sqft: 1080, lotSqft: null, yearBuilt: 2020, propertyType: "CONDO",
    features: ["doorman", "elevator", "rooftop", "pet-friendly", "ac", "in-unit-laundry"],
    description: "Modern two-bed loft in a brick conversion, rooftop deck and dog wash.",
    photos: [], postedAt: ago(14),
  },
  {
    id: "mock:sea-005", source: "mock", mode: "BUY", price: 67500000, address: "9 Ballard Heights",
    hood: "Ballard", city: "Seattle, WA", state: "WA", zip: "98107", lat: 47.6688, lng: -122.3845,
    beds: 3, baths: 2.5, sqft: 1680, lotSqft: 3200, yearBuilt: 2015, propertyType: "TOWNHOME",
    features: ["new-build", "garage", "rooftop", "ac"],
    description: "Newer Ballard townhome, three-stop rooftop deck with downtown views.",
    photos: [], postedAt: ago(22),
  },
  {
    id: "mock:sea-006", source: "mock", mode: "RENT", price: 215000, address: "4101 Brooklyn Ave NE",
    hood: "U District", city: "Seattle, WA", state: "WA", zip: "98105", lat: 47.6587, lng: -122.3137,
    beds: 1, baths: 1, sqft: 620, lotSqft: null, yearBuilt: 2019, propertyType: "APARTMENT",
    features: ["pet-friendly", "in-unit-laundry", "transit", "walkable"],
    description: "U District studio-plus, steps from light rail.",
    photos: [], postedAt: ago(40),
  },
  {
    id: "mock:sea-007", source: "mock", mode: "BUY", price: 118000000, address: "31 Magnolia Bluff",
    hood: "Magnolia", city: "Seattle, WA", state: "WA", zip: "98199", lat: 47.6489, lng: -122.4019,
    beds: 5, baths: 3.5, sqft: 3200, lotSqft: 8200, yearBuilt: 1972, propertyType: "HOUSE",
    features: ["garden", "garage", "fireplace", "basement", "fenced-yard"],
    description: "View home on the bluff with mature gardens and a finished walkout basement.",
    photos: [], postedAt: ago(30),
  },
  {
    id: "mock:sea-008", source: "mock", mode: "RENT", price: 245000, address: "1801 Alaskan Way #1101",
    hood: "Belltown", city: "Seattle, WA", state: "WA", zip: "98101", lat: 47.6131, lng: -122.3486,
    beds: 1, baths: 1, sqft: 690, lotSqft: null, yearBuilt: 2010, propertyType: "CONDO",
    features: ["doorman", "elevator", "pool", "ac", "transit"],
    description: "Belltown one-bed with bay views, building amenities include pool and gym.",
    photos: [], postedAt: ago(60),
  },
  {
    id: "mock:sea-009", source: "mock", mode: "BUY", price: 58200000, address: "104 Beacon Ave S",
    hood: "Beacon Hill", city: "Seattle, WA", state: "WA", zip: "98144", lat: 47.5783, lng: -122.3115,
    beds: 2, baths: 1, sqft: 1180, lotSqft: 4000, yearBuilt: 1947, propertyType: "HOUSE",
    features: ["garden", "fenced-yard", "transit"],
    description: "Beacon Hill bungalow with a south-facing yard, near the light rail station.",
    photos: [], postedAt: ago(80),
  },
  {
    id: "mock:sea-010", source: "mock", mode: "RENT", price: 410000, address: "5500 35th Ave NE",
    hood: "Wedgwood", city: "Seattle, WA", state: "WA", zip: "98105", lat: 47.6798, lng: -122.2877,
    beds: 4, baths: 2, sqft: 2050, lotSqft: 5400, yearBuilt: 1962, propertyType: "HOUSE",
    features: ["fenced-yard", "garage", "pet-friendly", "in-unit-laundry", "dishwasher"],
    description: "Family rental in Wedgwood: fenced yard, attached garage, walking distance to schools.",
    photos: [], postedAt: ago(12),
  },

  // ── Austin, TX ────────────────────────────────────────────
  {
    id: "mock:atx-001", source: "mock", mode: "BUY", price: 62500000, address: "1108 E 6th St",
    hood: "East Cesar Chavez", city: "Austin, TX", state: "TX", zip: "78702", lat: 30.2641, lng: -97.7307,
    beds: 3, baths: 2, sqft: 1620, lotSqft: 5100, yearBuilt: 2013, propertyType: "HOUSE",
    features: ["garden", "ac", "new-build", "walkable"],
    description: "Modern East side build, central courtyard, walking distance to Rainey.",
    photos: [], postedAt: ago(4),
  },
  {
    id: "mock:atx-002", source: "mock", mode: "RENT", price: 215000, address: "44 Rainey St #802",
    hood: "Rainey", city: "Austin, TX", state: "TX", zip: "78701", lat: 30.2592, lng: -97.7406,
    beds: 1, baths: 1, sqft: 720, lotSqft: null, yearBuilt: 2017, propertyType: "CONDO",
    features: ["doorman", "elevator", "pool", "ac", "in-unit-laundry"],
    description: "Highrise one-bed off Rainey, infinity pool deck on the 5th floor.",
    photos: [], postedAt: ago(7),
  },
  {
    id: "mock:atx-003", source: "mock", mode: "BUY", price: 79500000, address: "2400 W 35th St",
    hood: "Tarrytown", city: "Austin, TX", state: "TX", zip: "78703", lat: 30.3127, lng: -97.7635,
    beds: 4, baths: 3, sqft: 2480, lotSqft: 7600, yearBuilt: 1956, propertyType: "HOUSE",
    features: ["garden", "garage", "pool", "fenced-yard", "ac"],
    description: "Tarrytown ranch on a deep lot, mature trees, refreshed kitchen.",
    photos: [], postedAt: ago(16),
  },
  {
    id: "mock:atx-004", source: "mock", mode: "RENT", price: 175000, address: "5111 Manor Rd #14",
    hood: "Mueller", city: "Austin, TX", state: "TX", zip: "78723", lat: 30.2992, lng: -97.7034,
    beds: 1, baths: 1, sqft: 580, lotSqft: null, yearBuilt: 2019, propertyType: "APARTMENT",
    features: ["pet-friendly", "in-unit-laundry", "ac", "ev-charger", "walkable"],
    description: "Bright Mueller one-bed near the lake park, EV charger access in lot.",
    photos: [], postedAt: ago(20),
  },
  {
    id: "mock:atx-005", source: "mock", mode: "BUY", price: 51500000, address: "3220 Govalle Ave",
    hood: "Govalle", city: "Austin, TX", state: "TX", zip: "78702", lat: 30.2611, lng: -97.7022,
    beds: 2, baths: 1, sqft: 1080, lotSqft: 4400, yearBuilt: 1955, propertyType: "HOUSE",
    features: ["garden", "fenced-yard"],
    description: "Charming East side cottage, deep yard ready for an ADU.",
    photos: [], postedAt: ago(50),
  },
  {
    id: "mock:atx-006", source: "mock", mode: "RENT", price: 268000, address: "1010 W 6th St #3",
    hood: "West End", city: "Austin, TX", state: "TX", zip: "78703", lat: 30.2730, lng: -97.7574,
    beds: 2, baths: 2, sqft: 1140, lotSqft: null, yearBuilt: 2016, propertyType: "CONDO",
    features: ["balcony", "ac", "in-unit-laundry", "garage", "elevator"],
    description: "West end two-bed with downtown views, deeded parking spot.",
    photos: [], postedAt: ago(11),
  },
  {
    id: "mock:atx-007", source: "mock", mode: "BUY", price: 96500000, address: "5005 Balcones Dr",
    hood: "Allandale", city: "Austin, TX", state: "TX", zip: "78731", lat: 30.3367, lng: -97.7549,
    beds: 4, baths: 3.5, sqft: 2950, lotSqft: 9800, yearBuilt: 1974, propertyType: "HOUSE",
    features: ["pool", "garage", "ac", "fireplace"],
    description: "Allandale split-level with a sparkling pool, oversized garage with workshop.",
    photos: [], postedAt: ago(26),
  },
  {
    id: "mock:atx-008", source: "mock", mode: "RENT", price: 195000, address: "808 Nueces St #210",
    hood: "Downtown", city: "Austin, TX", state: "TX", zip: "78701", lat: 30.2737, lng: -97.7458,
    beds: 1, baths: 1, sqft: 660, lotSqft: null, yearBuilt: 2014, propertyType: "APARTMENT",
    features: ["transit", "walkable", "ac", "elevator"],
    description: "Quiet downtown one-bed in a smaller building, walking distance to UT.",
    photos: [], postedAt: ago(46),
  },
  {
    id: "mock:atx-009", source: "mock", mode: "BUY", price: 47200000, address: "13 Cherry Creek",
    hood: "South Lamar", city: "Austin, TX", state: "TX", zip: "78704", lat: 30.2381, lng: -97.7818,
    beds: 2, baths: 2, sqft: 1240, lotSqft: null, yearBuilt: 2014, propertyType: "TOWNHOME",
    features: ["garage", "ac", "new-build"],
    description: "South Lamar townhome with attached garage, walkable to coffee row.",
    photos: [], postedAt: ago(70),
  },
  {
    id: "mock:atx-010", source: "mock", mode: "RENT", price: 305000, address: "9012 Lakecliff Dr",
    hood: "Lakeway", city: "Austin, TX", state: "TX", zip: "78734", lat: 30.3661, lng: -97.9889,
    beds: 3, baths: 2, sqft: 1820, lotSqft: 7200, yearBuilt: 2003, propertyType: "HOUSE",
    features: ["pool", "garage", "fenced-yard", "ac", "pet-friendly"],
    description: "Lakeway home with a private pool, fenced backyard, and lake access.",
    photos: [], postedAt: ago(95),
  },
];
